name: E2E Test Kubernetes
on:
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_kubernetes.yml'
      - 'packages/backend-common/src/**'

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      CI: true
      KUBERNETES_TESTS: true

    steps:
      - uses: actions/checkout@v3

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.5.10
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: bootstrap kind
        uses: helm/kind-action@v1.4.0

      - name: kubernetes test
        working-directory: packages/backend-common
        run: yarn test:kubernetes
